In [4]:
import pandas as pd
import copy

### CREATE DATA

In [5]:

s = pd.Series([1, 2, 3, 4, 5])
print(s)
s_2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s_2)

data = {'name':['a', 'b', 'c', 'd', 'e'],'age':[1,2,3,4,5]}
df = pd.DataFrame(data)


print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
  name  age
0    a    1
1    b    2
2    c    3
3    d    4
4    e    5

### READ AND WRITE DATA

In [6]:

# df.to_csv('output.csv', index=False)
# df = pd.read_csv('output.csv')
print(df)

  name  age
0    a    1
1    b    2
2    c    3
3    d    4
4    e    5

### REVIEW DATA

In [7]:
print('head')
display(df.head())

print('tail')
display(df.tail(3))

print('info')
display(df.info())

print('describe')
display(df.describe())

print('shape')
display(df.shape)

print('columns')
display(df.columns)

print('index')
display(df.index)

head

  name  age
0    a    1
1    b    2
2    c    3
3    d    4
4    e    5

tail

  name  age
2    c    3
3    d    4
4    e    5

info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

None

describe

            age
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

shape

(5, 2)

columns

Index(['name', 'age'], dtype='object')

index

RangeIndex(start=0, stop=5, step=1)

### SELECT DATA

In [9]:
display(df['age'])
print('2 []')
display(df[['age']])
display(df[['name', 'age']])
display(df.iloc[0])
display(df.loc[0])
display(df.iloc[0:3])
display(df.loc[df['age'] > 23])

0    1
1    2
2    3
3    4
4    5
Name: age, dtype: int64

2 []

   age
0    1
1    2
2    3
3    4
4    5

  name  age
0    a    1
1    b    2
2    c    3
3    d    4
4    e    5

name    a
age     1
Name: 0, dtype: object

name    a
age     1
Name: 0, dtype: object

  name  age
0    a    1
1    b    2
2    c    3

Empty DataFrame
Columns: [name, age]
Index: []

### ADD, REMOVE AND CHANGE DATA

In [51]:

df['city'] = ['San Francisco', 'Tehran', 'Qom', 'NY', 'Tabriz']
main = copy.copy(df)

df.loc[0,'city'] = 'LA'
df

df.drop('city', axis=1, inplace=True)
df
df.drop(0, axis=0, inplace=True)      
df

  name  age
1    b    2
2    c    3
3    d    4
4    e    5

### ORDERING AND GROUPING

In [74]:
df = copy.copy(main)
df.loc[0, 'city'] = 'Tehran'
display(df.sort_values(by='age', ascending=False))

display(df.groupby('city')['age'].mean())


display(df.groupby('city').agg({'age':['mean','median','max','min','count']}))
display(df.agg({'age':['mean','median','max','min','count']}))

  name  age    city
4    e    5  Tabriz
3    d    4      NY
2    c    3     Qom
1    b    2  Tehran
0    a    1  Tehran

city
NY        4.0
Qom       3.0
Tabriz    5.0
Tehran    1.5
Name: age, dtype: float64

        age
       mean median max min count
city
NY      4.0    4.0   4   4     1
Qom     3.0    3.0   3   3     1
Tabriz  5.0    5.0   5   5     1
Tehran  1.5    1.5   2   1     2

        age
mean    3.0
median  3.0
max     5.0
min     1.0
count   5.0

### Data cleansing

In [77]:
df.loc[0,'city'] = None
# df.loc[0,'name'] = 'a'
display(df)
df.isnull().sum()     
# isnull() -> True and False
# isnull().sum() -> sum of all null values

# df.dropna(inplace=True) # delete rows have Nona value
# df.dropna(how'all', inplace=True) # delete rows that all columns is Nona
# df.dropna(axis=1, inplace=True) # delete columns that have None value 


# df.fillna(0, inplace=True) # fill None values with certain value
# df.fillna({'name': 'Unknown', 'age': df['age'].mean()}, inplace=True)
   
   # or fill None value with before or after value
# df.fillna(method='ffill', inplace=True)
# df.fillna(method='bfill', inplace=True)

  name  age    city
0    a    1    None
1    b    2  Tehran
2    c    3     Qom
3    d    4      NY
4    e    5  Tabriz

name    0
age     0
city    1
dtype: int64

### Merge and connect

In [ ]:
pd.concat([df1, df2])                       # اتصال عمودی
pd.merge(df1, df2, on='id', how='inner')    # ادغام بر اساس ستون id

### functions

In [ ]:
df['age_plus10'] = df['age'].apply(lambda x: x + 10)
df.applymap(str)   # اعمال تابع روی همه‌ی خانه‌ها

### Quick statistical and visual summary

In [ ]:
df['age'].mean()     # میانگین
df['age'].value_counts()  # تعداد تکرار هر مقدار
df.plot(kind='bar')   # نمودار ساده (با matplotlib)

### DARA FRAME